package net.cozystudios.cozystudioscore.entity.animations;

import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;

public class ModFernlingAnimations {

    public static final Animation FERNLING_WALKING = Animation.Builder.create(1f).looping()
            .addBoneAnimation("left_arm",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(40f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.08333f, AnimationHelper.createRotationalVector(34.64f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.16667f, AnimationHelper.createRotationalVector(20f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.33333f, AnimationHelper.createRotationalVector(-20f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.41667f, AnimationHelper.createRotationalVector(-34.64f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(-40f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.58333f, AnimationHelper.createRotationalVector(-34.64f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.66667f, AnimationHelper.createRotationalVector(-20f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.83333f, AnimationHelper.createRotationalVector(20f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.91667f, AnimationHelper.createRotationalVector(34.64f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(40f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("right_arm",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(-40f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.08333f, AnimationHelper.createRotationalVector(-34.64f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.16667f, AnimationHelper.createRotationalVector(-20f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.33333f, AnimationHelper.createRotationalVector(20f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.41667f, AnimationHelper.createRotationalVector(34.64f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(40f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.58333f, AnimationHelper.createRotationalVector(34.64f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.66667f, AnimationHelper.createRotationalVector(20f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.83333f, AnimationHelper.createRotationalVector(-20f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.91667f, AnimationHelper.createRotationalVector(-34.64f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(-40f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("left_leg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(-25f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.08333f, AnimationHelper.createRotationalVector(-19.64f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.16667f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(15f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.33333f, AnimationHelper.createRotationalVector(35f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.41667f, AnimationHelper.createRotationalVector(49.64f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(55f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.58333f, AnimationHelper.createRotationalVector(49.64f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.66667f, AnimationHelper.createRotationalVector(35f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(15f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.83333f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.91667f, AnimationHelper.createRotationalVector(-19.64f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(-25f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("right_leg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(55f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.08333f, AnimationHelper.createRotationalVector(49.64f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.16667f, AnimationHelper.createRotationalVector(35f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(15f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.33333f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.41667f, AnimationHelper.createRotationalVector(-19.64f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(-25f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.58333f, AnimationHelper.createRotationalVector(-19.64f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.66667f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(15f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.83333f, AnimationHelper.createRotationalVector(35f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.91667f, AnimationHelper.createRotationalVector(49.64f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(55f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("fernling",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.08333f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.16667f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.33333f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.41667f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.58333f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.66667f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.83333f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.91667f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("body",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.08333f, AnimationHelper.createTranslationalVector(0f, -0.43f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.16667f, AnimationHelper.createTranslationalVector(0f, -0.43f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.33333f, AnimationHelper.createTranslationalVector(0f, 0.43f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.41667f, AnimationHelper.createTranslationalVector(0f, 0.43f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.58333f, AnimationHelper.createTranslationalVector(0f, -0.43f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.66667f, AnimationHelper.createTranslationalVector(0f, -0.43f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.83333f, AnimationHelper.createTranslationalVector(0f, 0.43f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.91667f, AnimationHelper.createTranslationalVector(0f, 0.43f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("body_2",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.08333f, AnimationHelper.createRotationalVector(0f, 0f, 2.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.16667f, AnimationHelper.createRotationalVector(0f, 0f, 4.33f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, 5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.33333f, AnimationHelper.createRotationalVector(0f, 0f, 4.33f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.41667f, AnimationHelper.createRotationalVector(0f, 0f, 2.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.58333f, AnimationHelper.createRotationalVector(0f, 0f, -2.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.66667f, AnimationHelper.createRotationalVector(0f, 0f, -4.33f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, -5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.83333f, AnimationHelper.createRotationalVector(0f, 0f, -4.33f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.91667f, AnimationHelper.createRotationalVector(0f, 0f, -2.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("body_2",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1.05f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.08333f, AnimationHelper.createScalingVector(1f, 1.03f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.16667f, AnimationHelper.createScalingVector(1f, 0.98f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createScalingVector(1f, 0.95f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.33333f, AnimationHelper.createScalingVector(1f, 0.98f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.41667f, AnimationHelper.createScalingVector(1f, 1.03f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createScalingVector(1f, 1.05f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.58333f, AnimationHelper.createScalingVector(1f, 1.03f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.66667f, AnimationHelper.createScalingVector(1f, 0.98f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createScalingVector(1f, 0.95f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.83333f, AnimationHelper.createScalingVector(1f, 0.98f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.91667f, AnimationHelper.createScalingVector(1f, 1.03f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createScalingVector(1f, 1.05f, 1f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("head",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.08333f, AnimationHelper.createRotationalVector(-2.5f, 0f, 1.73f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.16667f, AnimationHelper.createRotationalVector(2.5f, 0f, 1.73f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.33333f, AnimationHelper.createRotationalVector(2.5f, 0f, -1.73f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.41667f, AnimationHelper.createRotationalVector(-2.5f, 0f, -1.73f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.58333f, AnimationHelper.createRotationalVector(-2.5f, 0f, 1.73f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.66667f, AnimationHelper.createRotationalVector(2.5f, 0f, 1.73f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.83333f, AnimationHelper.createRotationalVector(2.5f, 0f, -1.73f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.91667f, AnimationHelper.createRotationalVector(-2.5f, 0f, -1.73f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR))).build();
    public static final Animation FERNLING_IDLE = Animation.Builder.create(2f).looping()
            .addBoneAnimation("left_arm",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, -5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1f, AnimationHelper.createRotationalVector(0f, 0f, -6.55f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createRotationalVector(0f, 0f, -7.94f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3f, AnimationHelper.createRotationalVector(0f, 0f, -9.05f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createRotationalVector(0f, 0f, -9.76f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, -10f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createRotationalVector(0f, 0f, -9.76f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createRotationalVector(0f, 0f, -9.05f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8f, AnimationHelper.createRotationalVector(0f, 0f, -7.94f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9f, AnimationHelper.createRotationalVector(0f, 0f, -6.55f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, -5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.1f, AnimationHelper.createRotationalVector(0f, 0f, -3.45f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2f, AnimationHelper.createRotationalVector(0f, 0f, -2.06f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.3f, AnimationHelper.createRotationalVector(0f, 0f, -0.95f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4f, AnimationHelper.createRotationalVector(0f, 0f, -0.24f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.6f, AnimationHelper.createRotationalVector(0f, 0f, -0.24f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.7f, AnimationHelper.createRotationalVector(0f, 0f, -0.95f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.8f, AnimationHelper.createRotationalVector(0f, 0f, -2.06f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.9f, AnimationHelper.createRotationalVector(0f, 0f, -3.45f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, -5f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("right_arm",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1f, AnimationHelper.createRotationalVector(0f, 0f, 6.55f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createRotationalVector(0f, 0f, 7.94f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3f, AnimationHelper.createRotationalVector(0f, 0f, 9.05f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createRotationalVector(0f, 0f, 9.76f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 10f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createRotationalVector(0f, 0f, 9.76f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createRotationalVector(0f, 0f, 9.05f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8f, AnimationHelper.createRotationalVector(0f, 0f, 7.94f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9f, AnimationHelper.createRotationalVector(0f, 0f, 6.55f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.1f, AnimationHelper.createRotationalVector(0f, 0f, 3.45f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2f, AnimationHelper.createRotationalVector(0f, 0f, 2.06f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.3f, AnimationHelper.createRotationalVector(0f, 0f, 0.95f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4f, AnimationHelper.createRotationalVector(0f, 0f, 0.24f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.6f, AnimationHelper.createRotationalVector(0f, 0f, 0.24f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.7f, AnimationHelper.createRotationalVector(0f, 0f, 0.95f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.8f, AnimationHelper.createRotationalVector(0f, 0f, 2.06f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.9f, AnimationHelper.createRotationalVector(0f, 0f, 3.45f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 5f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("head",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1f, AnimationHelper.createRotationalVector(-1.55f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createRotationalVector(-2.94f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3f, AnimationHelper.createRotationalVector(-4.05f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createRotationalVector(-4.76f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createRotationalVector(-4.76f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createRotationalVector(-4.05f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8f, AnimationHelper.createRotationalVector(-2.94f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9f, AnimationHelper.createRotationalVector(-1.55f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.1f, AnimationHelper.createRotationalVector(1.55f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2f, AnimationHelper.createRotationalVector(2.94f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.3f, AnimationHelper.createRotationalVector(4.05f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4f, AnimationHelper.createRotationalVector(4.76f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.6f, AnimationHelper.createRotationalVector(4.76f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.7f, AnimationHelper.createRotationalVector(4.05f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.8f, AnimationHelper.createRotationalVector(2.94f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.9f, AnimationHelper.createRotationalVector(1.55f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("body_2",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0.2f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1f, AnimationHelper.createTranslationalVector(0f, 0.19f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createTranslationalVector(0f, 0.16f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3f, AnimationHelper.createTranslationalVector(0f, 0.12f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createTranslationalVector(0f, 0.06f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createTranslationalVector(0f, -0.06f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createTranslationalVector(0f, -0.12f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8f, AnimationHelper.createTranslationalVector(0f, -0.16f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9f, AnimationHelper.createTranslationalVector(0f, -0.19f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, -0.2f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.1f, AnimationHelper.createTranslationalVector(0f, -0.19f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2f, AnimationHelper.createTranslationalVector(0f, -0.16f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.3f, AnimationHelper.createTranslationalVector(0f, -0.12f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4f, AnimationHelper.createTranslationalVector(0f, -0.06f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.6f, AnimationHelper.createTranslationalVector(0f, 0.06f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.7f, AnimationHelper.createTranslationalVector(0f, 0.12f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.8f, AnimationHelper.createTranslationalVector(0f, 0.16f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.9f, AnimationHelper.createTranslationalVector(0f, 0.19f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0.2f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("body_2",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1f, AnimationHelper.createRotationalVector(0f, 0f, 1.9f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createRotationalVector(0f, 0f, 1.62f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3f, AnimationHelper.createRotationalVector(0f, 0f, 1.18f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createRotationalVector(0f, 0f, 0.62f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createRotationalVector(0f, 0f, -0.62f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createRotationalVector(0f, 0f, -1.18f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8f, AnimationHelper.createRotationalVector(0f, 0f, -1.62f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9f, AnimationHelper.createRotationalVector(0f, 0f, -1.9f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, -2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.1f, AnimationHelper.createRotationalVector(0f, 0f, -1.9f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2f, AnimationHelper.createRotationalVector(0f, 0f, -1.62f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.3f, AnimationHelper.createRotationalVector(0f, 0f, -1.18f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4f, AnimationHelper.createRotationalVector(0f, 0f, -0.62f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.6f, AnimationHelper.createRotationalVector(0f, 0f, 0.62f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.7f, AnimationHelper.createRotationalVector(0f, 0f, 1.18f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.8f, AnimationHelper.createRotationalVector(0f, 0f, 1.62f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.9f, AnimationHelper.createRotationalVector(0f, 0f, 1.9f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 2f),
                                    Transformation.Interpolations.LINEAR))).build();
    public static final Animation SLEEPING_200 = Animation.Builder.create(2f).looping()
            .addBoneAnimation("1",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1f, AnimationHelper.createScalingVector(1.1f, 1.1f, 1.1f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("plant_entity",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -4f, -2f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("body",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -0.75f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("body",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(92.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("bone",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("left_arm",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0.75f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("left_arm",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(-165.22f, -3.32f, 17.35f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("right_arm",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0.75f, 2f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("right_arm",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(-164.92f, -1.38f, 23.71f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("head",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(1f, 1f, -2f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("head",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(-87.59f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("head_1",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(0f, AnimationHelper.createScalingVector(1.1f, 1.1f, 1.1f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("eyebrow_1",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -1.25f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, -0.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, -1.25f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("eyebrow_2",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -1.25f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, -0.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, -1.25f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("plant",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("left_leg",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, -1f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("left_leg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(-25f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("right_leg",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, -1f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("right_leg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(-25f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR))).build();
    public static final Animation FERNLING_SLEEPING = Animation.Builder.create(4f).looping()
            .addBoneAnimation("1",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1f, AnimationHelper.createScalingVector(1.1f, 1.1f, 1.1f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("plant_entity",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -4f, -2f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("body",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -0.75f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("body",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(92.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("bone",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("left_arm",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(1f, 1.5f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("left_arm",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(-167.82f, 9.02f, -30.98f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("right_arm",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0.75f, 2f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("right_arm",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(-164.92f, -1.38f, 23.71f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("head",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(1f, 2f, -0.5f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("head",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(-82.59f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1f, AnimationHelper.createRotationalVector(-82.65f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createRotationalVector(-82.83f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3f, AnimationHelper.createRotationalVector(-83.13f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createRotationalVector(-83.54f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(-84.05f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createRotationalVector(-84.65f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createRotationalVector(-85.32f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8f, AnimationHelper.createRotationalVector(-86.04f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9f, AnimationHelper.createRotationalVector(-86.8f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(-87.59f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.1f, AnimationHelper.createRotationalVector(-88.37f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2f, AnimationHelper.createRotationalVector(-89.13f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.3f, AnimationHelper.createRotationalVector(-89.86f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4f, AnimationHelper.createRotationalVector(-90.52f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(-91.12f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.6f, AnimationHelper.createRotationalVector(-91.63f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.7f, AnimationHelper.createRotationalVector(-92.04f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.8f, AnimationHelper.createRotationalVector(-92.34f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.9f, AnimationHelper.createRotationalVector(-92.52f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(-92.59f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.1f, AnimationHelper.createRotationalVector(-92.52f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.2f, AnimationHelper.createRotationalVector(-92.34f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.3f, AnimationHelper.createRotationalVector(-92.04f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.4f, AnimationHelper.createRotationalVector(-91.63f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.5f, AnimationHelper.createRotationalVector(-91.12f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.6f, AnimationHelper.createRotationalVector(-90.52f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.7f, AnimationHelper.createRotationalVector(-89.86f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.8f, AnimationHelper.createRotationalVector(-89.13f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.9f, AnimationHelper.createRotationalVector(-88.37f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3f, AnimationHelper.createRotationalVector(-87.59f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.1f, AnimationHelper.createRotationalVector(-86.8f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.2f, AnimationHelper.createRotationalVector(-86.04f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.3f, AnimationHelper.createRotationalVector(-85.32f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.4f, AnimationHelper.createRotationalVector(-84.65f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.5f, AnimationHelper.createRotationalVector(-84.05f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.6f, AnimationHelper.createRotationalVector(-83.54f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.7f, AnimationHelper.createRotationalVector(-83.13f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.8f, AnimationHelper.createRotationalVector(-82.83f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.9f, AnimationHelper.createRotationalVector(-82.65f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(4f, AnimationHelper.createRotationalVector(-82.59f, -0.65f, 14.99f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("head_1",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(0f, AnimationHelper.createScalingVector(1.1f, 1.1f, 1.1f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("eyebrow_1",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1f, AnimationHelper.createTranslationalVector(0f, -0.58f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createTranslationalVector(0f, -0.65f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3f, AnimationHelper.createTranslationalVector(0f, -0.73f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createTranslationalVector(0f, -0.79f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, -0.85f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createTranslationalVector(0f, -0.9f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createTranslationalVector(0f, -0.95f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8f, AnimationHelper.createTranslationalVector(0f, -0.98f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9f, AnimationHelper.createTranslationalVector(0f, -0.99f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.1f, AnimationHelper.createTranslationalVector(0f, -0.99f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2f, AnimationHelper.createTranslationalVector(0f, -0.98f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.3f, AnimationHelper.createTranslationalVector(0f, -0.95f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4f, AnimationHelper.createTranslationalVector(0f, -0.9f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, -0.85f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.6f, AnimationHelper.createTranslationalVector(0f, -0.79f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.7f, AnimationHelper.createTranslationalVector(0f, -0.73f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.8f, AnimationHelper.createTranslationalVector(0f, -0.65f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.9f, AnimationHelper.createTranslationalVector(0f, -0.58f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.1f, AnimationHelper.createTranslationalVector(0f, -0.42f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.2f, AnimationHelper.createTranslationalVector(0f, -0.35f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.3f, AnimationHelper.createTranslationalVector(0f, -0.27f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.4f, AnimationHelper.createTranslationalVector(0f, -0.21f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.5f, AnimationHelper.createTranslationalVector(0f, -0.15f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.6f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.7f, AnimationHelper.createTranslationalVector(0f, -0.05f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.8f, AnimationHelper.createTranslationalVector(0f, -0.02f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.9f, AnimationHelper.createTranslationalVector(0f, -0.01f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.1f, AnimationHelper.createTranslationalVector(0f, -0.01f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.2f, AnimationHelper.createTranslationalVector(0f, -0.02f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.3f, AnimationHelper.createTranslationalVector(0f, -0.05f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.4f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.5f, AnimationHelper.createTranslationalVector(0f, -0.15f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.6f, AnimationHelper.createTranslationalVector(0f, -0.21f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.7f, AnimationHelper.createTranslationalVector(0f, -0.27f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.8f, AnimationHelper.createTranslationalVector(0f, -0.35f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.9f, AnimationHelper.createTranslationalVector(0f, -0.42f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(4f, AnimationHelper.createTranslationalVector(0f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("eyebrow_2",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1f, AnimationHelper.createTranslationalVector(0f, -0.58f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createTranslationalVector(0f, -0.65f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3f, AnimationHelper.createTranslationalVector(0f, -0.73f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createTranslationalVector(0f, -0.79f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, -0.85f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createTranslationalVector(0f, -0.9f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createTranslationalVector(0f, -0.95f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8f, AnimationHelper.createTranslationalVector(0f, -0.98f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9f, AnimationHelper.createTranslationalVector(0f, -0.99f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.1f, AnimationHelper.createTranslationalVector(0f, -0.99f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2f, AnimationHelper.createTranslationalVector(0f, -0.98f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.3f, AnimationHelper.createTranslationalVector(0f, -0.95f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4f, AnimationHelper.createTranslationalVector(0f, -0.9f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, -0.85f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.6f, AnimationHelper.createTranslationalVector(0f, -0.79f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.7f, AnimationHelper.createTranslationalVector(0f, -0.73f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.8f, AnimationHelper.createTranslationalVector(0f, -0.65f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.9f, AnimationHelper.createTranslationalVector(0f, -0.58f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.1f, AnimationHelper.createTranslationalVector(0f, -0.42f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.2f, AnimationHelper.createTranslationalVector(0f, -0.35f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.3f, AnimationHelper.createTranslationalVector(0f, -0.27f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.4f, AnimationHelper.createTranslationalVector(0f, -0.21f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.5f, AnimationHelper.createTranslationalVector(0f, -0.15f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.6f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.7f, AnimationHelper.createTranslationalVector(0f, -0.05f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.8f, AnimationHelper.createTranslationalVector(0f, -0.02f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.9f, AnimationHelper.createTranslationalVector(0f, -0.01f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.1f, AnimationHelper.createTranslationalVector(0f, -0.01f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.2f, AnimationHelper.createTranslationalVector(0f, -0.02f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.3f, AnimationHelper.createTranslationalVector(0f, -0.05f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.4f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.5f, AnimationHelper.createTranslationalVector(0f, -0.15f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.6f, AnimationHelper.createTranslationalVector(0f, -0.21f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.7f, AnimationHelper.createTranslationalVector(0f, -0.27f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.8f, AnimationHelper.createTranslationalVector(0f, -0.35f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.9f, AnimationHelper.createTranslationalVector(0f, -0.42f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(4f, AnimationHelper.createTranslationalVector(0f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("left_leg",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, -1f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("left_leg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(-25f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("right_leg",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, -1f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("right_leg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(-25f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("fernling",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -4f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("torso",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(0f, AnimationHelper.createScalingVector(1.03f, 1.03f, 1.03f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1f, AnimationHelper.createScalingVector(1.02f, 1.02f, 1.02f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createScalingVector(1.02f, 1.02f, 1.02f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3f, AnimationHelper.createScalingVector(1.02f, 1.02f, 1.02f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createScalingVector(1.02f, 1.02f, 1.02f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createScalingVector(1.02f, 1.02f, 1.02f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createScalingVector(1.01f, 1.01f, 1.01f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createScalingVector(1.01f, 1.01f, 1.01f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8f, AnimationHelper.createScalingVector(1.01f, 1.01f, 1.01f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.1f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2f, AnimationHelper.createScalingVector(0.99f, 0.99f, 0.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.3f, AnimationHelper.createScalingVector(0.99f, 0.99f, 0.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4f, AnimationHelper.createScalingVector(0.99f, 0.99f, 0.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createScalingVector(0.98f, 0.98f, 0.98f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.6f, AnimationHelper.createScalingVector(0.98f, 0.98f, 0.98f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.7f, AnimationHelper.createScalingVector(0.98f, 0.98f, 0.98f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.8f, AnimationHelper.createScalingVector(0.98f, 0.98f, 0.98f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.9f, AnimationHelper.createScalingVector(0.98f, 0.98f, 0.98f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createScalingVector(0.98f, 0.98f, 0.98f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.1f, AnimationHelper.createScalingVector(0.98f, 0.98f, 0.98f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.2f, AnimationHelper.createScalingVector(0.98f, 0.98f, 0.98f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.3f, AnimationHelper.createScalingVector(0.98f, 0.98f, 0.98f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.4f, AnimationHelper.createScalingVector(0.98f, 0.98f, 0.98f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.5f, AnimationHelper.createScalingVector(0.98f, 0.98f, 0.98f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.6f, AnimationHelper.createScalingVector(0.99f, 0.99f, 0.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.7f, AnimationHelper.createScalingVector(0.99f, 0.99f, 0.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.8f, AnimationHelper.createScalingVector(0.99f, 0.99f, 0.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.9f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.1f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.2f, AnimationHelper.createScalingVector(1.01f, 1.01f, 1.01f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.3f, AnimationHelper.createScalingVector(1.01f, 1.01f, 1.01f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.4f, AnimationHelper.createScalingVector(1.01f, 1.01f, 1.01f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.5f, AnimationHelper.createScalingVector(1.02f, 1.02f, 1.02f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.6f, AnimationHelper.createScalingVector(1.02f, 1.02f, 1.02f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.7f, AnimationHelper.createScalingVector(1.02f, 1.02f, 1.02f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.8f, AnimationHelper.createScalingVector(1.02f, 1.02f, 1.02f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.9f, AnimationHelper.createScalingVector(1.02f, 1.02f, 1.02f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(4f, AnimationHelper.createScalingVector(1.03f, 1.03f, 1.03f),
                                    Transformation.Interpolations.LINEAR))).build();
}
